export interface Review {
    id: string;
    authorName: string;
    rating: number;
    text: string;
    date: string;
    source: "Google" | "ProvenExpert";
    location?: string;
    avatarUrl?: string;
}

export const reviewsData: Review[] = [
    {
        id: "1",
        authorName: "Jens Brandenburger",
        rating: 5,
        text: "Schlüsseldienst ist Top, vor allem blitzschnell, sehr freundlich und hilfsbereit! Keine Wartezeit ...",
        date: "Vor 1 Woche",
        source: "Google",
    },
    {
        id: "2",
        authorName: "Umutcan Tezgel",
        rating: 5,
        text: "Innerhalb von 15 Minuten vor Ort.",
        date: "Vor 2 Wochen",
        source: "Google",
    },
    {
        id: "3",
        authorName: "Emelie Herbel",
        rating: 5,
        text: "Einfach nur super freundlich! Wir standen in Wetzlar und haben dringend einen guten Schlüsseldienst gebraucht \u2013 und sind so froh, diesen hier gefunden zu haben!",
        date: "Vor 2 Wochen",
        source: "Google",
        location: "Wetzlar",
    },
    {
        id: "4",
        authorName: "Fabrice-Andre Lachnit",
        rating: 5,
        text: "Top!",
        date: "Vor 2 Wochen",
        source: "Google",
    },
    {
        id: "5",
        authorName: "Sahar Koob",
        rating: 5,
        text: "Super schneller und zuverlässiger Service! Ich war ausgesperrt und der Schlüsseldienst war innerhalb kürzester Zeit vor Ort. Die Tür wurde professionell und ohne Beschädigungen geöffnet.",
        date: "Vor 3 Wochen",
        source: "Google",
    },
    {
        id: "6",
        authorName: "Mi Due",
        rating: 5,
        text: "Freundlicher und seriöser Kontakt am Telefon, Preise auf der Webseite transparent erklärt.",
        date: "Vor 1 Monat",
        source: "Google",
    },
    {
        id: "7",
        authorName: "Alexandra",
        rating: 5,
        text: "Sehr zuvorkommend und professionell. Wirklich ganz toller und außergewöhnlicher Service!!! Ich bin unendlich dankbar für die Geduld und das Engagement, was mir heute entgegengebracht wurde! Vielen, vielen Dank!",
        date: "Vor 1 Monat",
        source: "Google",
    },
    {
        id: "8",
        authorName: "Thomas S.",
        rating: 5,
        text: "Der Schlüsseldienst war eben vor Ort, super freundlich und hat die Tür komplett ohne Beschädigungen geöffnet. Absolut zuverlässig und professionell. Ich bin sehr zufrieden und kann den Service uneingeschränkt weiterempfehlen.",
        date: "Vor 2 Monaten",
        source: "Google",
    },
    {
        id: "9",
        authorName: "Coco Lores",
        rating: 5,
        text: "Der nette Mann der mir eben meine Tür geöffnet hat, hat seine Arbeit top gemacht! Klare Empfehlung!",
        date: "Vor 3 Monaten",
        source: "Google",
    },
    {
        id: "10",
        authorName: "Paula",
        rating: 5,
        text: "Mina war am Telefon und in Person super freundlich, hat alle Fragen beantwortet, sich mit dem Kollegen abgesprochen damit er früher da sein kann und war dann schnell vor Ort.",
        date: "Vor 4 Monaten",
        source: "Google",
    },
    {
        id: "11",
        authorName: "Tim Staudt",
        rating: 5,
        text: "Wir sind mit dem Schlüsseldienst überaus zufrieden. Ihr Mitarbeiter, Herr Saad, hat sich als kompetent, verbindlich und zuverlässig erwiesen und hat uns mit allen Problemen zielsicher beiseite gestanden.",
        date: "Vor 5 Monaten",
        source: "Google",
    },
    {
        id: "12",
        authorName: "Jay",
        rating: 5,
        text: "Super Firma und danke an Mina, dass er um 4:45 nachts noch gekommen ist trotz 45 min Fahrt.",
        date: "Vor 5 Monaten",
        source: "Google",
    },
    {
        id: "13",
        authorName: "Sa Sa",
        rating: 5,
        text: "Der Schlüsseldienst ist echt Top! Er war sehr schnell vor Ort und konnte mir meinen abgebrochenen Schlüssel aus dem Schloss entfernen.",
        date: "Vor 6 Monaten",
        source: "Google",
    },
    {
        id: "14",
        authorName: "Maximilian Meister",
        rating: 5,
        text: "Schnell, nett, zuverlässig, freundlich \u2013 alles bestens.",
        date: "Vor 6 Monaten",
        source: "Google",
    },
    {
        id: "15",
        authorName: "Tasha",
        rating: 5,
        text: "Herr M. ist sofort ans Telefon gegangen, war schnell vor Ort und hat die Tür zügig und professionell geöffnet. Sehr freundlich und zuverlässig \u2013 absolut empfehlenswert!",
        date: "Vor 8 Monaten",
        source: "Google",
    },
    {
        id: "16",
        authorName: "Frogger",
        rating: 5,
        text: "Schneller freundlicher Service und Tür aufbekommen ohne Schaden anzurichten. Alles in allem ein empfehlenswerter Schlüsseldienst.",
        date: "Vor 9 Monaten",
        source: "Google",
    },
    {
        id: "17",
        authorName: "Christine Civic",
        rating: 5,
        text: "Schnell, freundlich und professionell! Der Schlüsseldienst war zügig vor Ort und hat meine Tür ohne Schaden geöffnet. Absolut zufrieden \u2013 sehr empfehlenswert!",
        date: "Vor 10 Monaten",
        source: "Google",
    },
    {
        id: "18",
        authorName: "Axel Mugler",
        rating: 5,
        text: "Man hört ja leider sehr viel Schlechtes über Schlüsseldienste, und deswegen waren wir ein wenig in Sorge, als wir nun auch die Dienste eines Schlüsseldienstes in Anspruch nehmen mussten. Aber alles lief einwandfrei.",
        date: "Vor 10 Monaten",
        source: "Google",
    },
    {
        id: "19",
        authorName: "Francesca Bischof",
        rating: 5,
        text: "Perfekter Service! Extrem freundlich und zuvorkommend. Bei jedem Arbeitsschritt und preislichen Veränderungen absolut transparent und fair.",
        date: "Vor 10 Monaten",
        source: "Google",
    },
    {
        id: "20",
        authorName: "Uschi Gombert",
        rating: 4,
        text: "Zuverlässig und freundlich und schnell in der Not da, wenn man sich ausgesperrt hat.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "21",
        authorName: "Anita Berisha",
        rating: 5,
        text: "Absolut zu empfehlen! Preis-Leistung total angemessen, saubere Arbeit. Obwohl es Samstag ist, war er innerhalb 15 Minuten nach dem Anruf vor Ort.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "22",
        authorName: "Keno Hegemann",
        rating: 5,
        text: "Ehrlich, schnell und menschlich \u2013 genau das, was man sich in einer Notlage wünscht.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "23",
        authorName: "Alice Wonder",
        rating: 5,
        text: "Kann ich nur empfehlen, er war pünktlich da, hat die Tür schnell aufbekommen und war super nett.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "24",
        authorName: "S Z",
        rating: 5,
        text: "",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "25",
        authorName: "Denise Winkler",
        rating: 5,
        text: "",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "26",
        authorName: "Davide",
        rating: 5,
        text: "Ich hatte eine ausgezeichnete Erfahrung mit diesem Schlüsselnotdienst. Als ich mich ausgesperrt hatte, war ich zunächst besorgt, dass ich lange warten oder viel bezahlen müsste. Aber alles lief reibungslos.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "27",
        authorName: "Kate",
        rating: 5,
        text: "Schneller und zuverlässiger Service!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "28",
        authorName: "Tarek Habid",
        rating: 5,
        text: "Hervorragender Service! Ich hatte mich spät abends ausgesperrt und der Schlüsseldienst war sofort zur Stelle.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "29",
        authorName: "Deniz Kaplan",
        rating: 5,
        text: "Ich kann Mina Schlüsseldienst in Wetzlar nur wärmstens empfehlen! Der Service war außergewöhnlich schnell \u2013 innerhalb kürzester Zeit vor Ort und unser Problem war sofort gelöst.",
        date: "Vor 1 Jahr",
        source: "Google",
        location: "Wetzlar",
    },
    {
        id: "30",
        authorName: "Carlos Sanchez",
        rating: 5,
        text: "Tür zugefallen und in der Kälte ausgeschlossen. Er war innerhalb von 20 Minuten da und hat uns geholfen. Wir waren aufgrund der Medienberichte über schwarze Schafe in der Branche zunächst skeptisch, aber alles lief fair ab.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "31",
        authorName: "I I",
        rating: 5,
        text: "Ich habe mich leider ausgesperrt und musste einen Schlüsseldienst rufen. Der nette Herr war bereits nach 20 Minuten da und hat die Tür schnell und professionell geöffnet.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "32",
        authorName: "Vencislav Redling",
        rating: 5,
        text: "Einen ehrlicheren Schlüsseldienst kann man sich nicht wünschen. Um 2 Uhr nachts hatte sich der Nachbar ausgesperrt und nach einem sehr netten Telefonat war der Schlüsseldienst schnell vor Ort.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "33",
        authorName: "Yoshi Yorgo",
        rating: 5,
        text: "Super Schlüsseldienst \u2013 schnell, fair und zuverlässig!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "34",
        authorName: "Roman",
        rating: 5,
        text: "Sehr zu empfehlen, der Kollege war super schnell da (ca. 20min) und die Tür war in 15min offen! Das Schloss wurde nicht beschädigt, einfach top.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "35",
        authorName: "Florence Boamah",
        rating: 5,
        text: "Thank you for helping my daughter out of the room when she got herself locked. He is very patient and communicates very well with us. Your help came really in time. We are grateful.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "36",
        authorName: "BR_ 27",
        rating: 5,
        text: "Kann ich nur empfehlen. Wir haben uns ausgesperrt und es war schon sehr spät, es hat keine 15 min gedauert nach unserem Telefonat, da konnte der nette Herr uns die Tür öffnen.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "37",
        authorName: "Artjom Lautenschläger",
        rating: 5,
        text: "Ich habe mich ausgesperrt und war echt in Panik, aber der Schlüsseldienst Wetzlar war super schnell da und hat mir geholfen.",
        date: "Vor 1 Jahr",
        source: "Google",
        location: "Wetzlar",
    },
    {
        id: "38",
        authorName: "S. K",
        rating: 5,
        text: "Der freundliche Kundenservice Hr. Mina kam sehr schnell. Vielen Dank für die hervorragende Arbeit! Kann ich nur weiterempfehlen!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "39",
        authorName: "Bernd Sperlich",
        rating: 5,
        text: "Sehr guter Service, mir wurde super schnell geholfen zu einem fairen Preis.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "40",
        authorName: "MD F",
        rating: 5,
        text: "Schnell, zuverlässig und vor allem der Preis wurde wie auf der Seite beschrieben eingehalten!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "41",
        authorName: "Hessen26",
        rating: 5,
        text: "Sehr empfehlenswert, schnelle und professionelle Arbeit, Preis-Leistung top.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "42",
        authorName: "Ekram H.",
        rating: 5,
        text: "Kann ich nur empfehlen, zuverlässiger Service und sehr faire Preise.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "43",
        authorName: "Ahmed Salman",
        rating: 5,
        text: "",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "44",
        authorName: "Oktay Yildiz",
        rating: 5,
        text: "",
        date: "Vor 8 Monaten",
        source: "Google",
    },
];

export const aggregateRating = {
    ratingValue: 5.0,
    reviewCount: 44,
};
