#!/bin/bash
# Ultrathink Bild-SEO: Batch-Umbenennung mit SEO-Naming
# Next.js <Image> konvertiert automatisch zu WebP/AVIF zur Laufzeit
# Daher kopieren wir die JPEGs mit korrektem SEO-Naming

SRC="/Users/umurey/Downloads/MS-Schl-sseldienst-main/MS-Bilder"
DST="/Users/umurey/Downloads/MS-Schl-sseldienst-main/public/images"

# Alte fehlgeschlagene Dateien bereinigen
rm -f "$DST"/*.webp 2>/dev/null

mkdir -p "$DST"

echo "═══════════════════════════════════════════════════"
echo "  PHASE 1: SEO-Batch-Umbenennung (43 JPEGs)"
echo "  Next.js optimiert automatisch zu WebP/AVIF"
echo "═══════════════════════════════════════════════════"

cp "$SRC/Schlüsselerstellungs Maschiene.jpeg" "$DST/schluessel-fraesmaschine-schluesseldienst-wetzlar.jpeg"
cp "$SRC/leeres Türschloss.jpeg" "$DST/leerer-schliesszylinder-tuerschloss-wetzlar.jpeg"
cp "$SRC/aufgebrochenes Türschloss vermessen.jpeg" "$DST/aufgebrochenes-tuerschloss-vermessung-wetzlar.jpeg"
cp "$SRC/Technik sicht auf das innere eines Türschloss.jpeg" "$DST/tuerschloss-innenleben-technik-nahaufnahme.jpeg"
cp "$SRC/Maschiene für die schlüssel erstellung.jpeg" "$DST/schluessel-kopierfraese-werkstatt-wetzlar.jpeg"
cp "$SRC/Hinter dem Kofferraum lächelnd in die Kamera schauen.jpeg" "$DST/mina-saad-schluesseldienst-wetzlar-einsatzfahrzeug.jpeg"
cp "$SRC/Installierter Tür eingang aus EdelstahlV1.jpeg" "$DST/edelstahl-tuereingang-montage-schluesseldienst.jpeg"
cp "$SRC/Klick schloss modern in einer alten Tür.jpeg" "$DST/elektronisches-tuerschloss-nachruestung-alte-tuer.jpeg"
cp "$SRC/3 Goldene und 3 Silberne Medallien aus neuer Perspektive.jpeg" "$DST/wetzlar-open-medaillen-gold-silber-nahaufnahme.jpeg"
cp "$SRC/Innere der Schlüsselschmiede.jpeg" "$DST/schluessel-schmiede-wetzlar-werkstatt-innenraum.jpeg"
cp "$SRC/Innere des Glasschrankes innerhalb der Schlüsselschmiede.jpeg" "$DST/schluessel-schmiede-wetzlar-glasvitrine-sortiment.jpeg"
cp "$SRC/Kaputtes verrostets Schloss.jpeg" "$DST/kaputtes-verrostetes-schloss-austausch-wetzlar.jpeg"
cp "$SRC/Kaputt Türschloss.jpeg" "$DST/defektes-tuerschloss-reparatur-schluesseldienst.jpeg"
cp "$SRC/Werkzeug vorbereiten im Kofferraum vom Auto.jpeg" "$DST/schluesseldienst-wetzlar-werkzeug-einsatzfahrzeug.jpeg"
cp "$SRC/Während der Arbeit oben an einer Tür.jpeg" "$DST/tueroeffnung-arbeit-obertuerband-schluesseldienst.jpeg"
cp "$SRC/Orginal Schlüssel mit Kopierter Version.jpeg" "$DST/original-schluessel-kopie-vergleich-wetzlar.jpeg"
cp "$SRC/weiteres Bild neben der Straße von Kopf bis Knie Bild.jpeg" "$DST/mina-saad-inhaber-schluessel-schmiede-portrait.jpeg"
cp "$SRC/Geöffnetes Schloss .jpeg" "$DST/geoeffnetes-schloss-tueroeffnung-wetzlar.jpeg"
cp "$SRC/weiteres Bild neben der Straße.jpeg" "$DST/mina-saad-schluesseldienst-wetzlar-outdoor-portrait.jpeg"
cp "$SRC/Mina Saad neben der Straße full body bild vertraulich.jpeg" "$DST/mina-saad-schluesseldienst-wetzlar-ganzkoerper.jpeg"
cp "$SRC/Kaputtes Türschoss durch aufbrechen.jpeg" "$DST/aufgebrochenes-tuerschloss-einbruchschaden-wetzlar.jpeg"
cp "$SRC/Minaa Saad Inhaber Selfie.jpeg" "$DST/mina-saad-inhaber-selfie-schluesseldienst-wetzlar.jpeg"
cp "$SRC/Medallie Sieger Wetzlar Open 2025.jpeg" "$DST/siegermedaille-wetzlar-open-2025-mina-saad.jpeg"
cp "$SRC/aufgebrochenen Türschloss von der Wand weg.jpeg" "$DST/demontiertes-tuerschloss-wandmontage-wetzlar.jpeg"
cp "$SRC/Glas Tür eingang mit Person während der Installation.jpeg" "$DST/glastuer-eingang-montage-schluesseldienst-wetzlar.jpeg"
cp "$SRC/Türschloss in einer Holz Tür.jpeg" "$DST/tuerschloss-holztuer-sicherheitstechnik-wetzlar.jpeg"
cp "$SRC/Mehrere hängende Schlüssel.jpeg" "$DST/schluessel-sortiment-haengend-schluessel-schmiede.jpeg"
cp "$SRC/Altertümlich Schön designtem Schlüssel.jpeg" "$DST/antiker-schluessel-design-schluessel-schmiede.jpeg"
cp "$SRC/Hängende Auto Schlüssel andere Perspektive.jpeg" "$DST/autoschluessel-sortiment-kfz-schluesseldienst-wetzlar.jpeg"
cp "$SRC/Mina Saad während der Arbeit.jpeg" "$DST/mina-saad-arbeitseinsatz-tueroeffnung-wetzlar.jpeg"
cp "$SRC/Prozess während Tür Öffnung.jpeg" "$DST/tueroeffnung-prozess-zerstoerungsfrei-wetzlar.jpeg"
cp "$SRC/Aufgebrochenes Tür Schloss.jpeg" "$DST/aufgebrochenes-sicherheitsschloss-wetzlar-einsatz.jpeg"
cp "$SRC/3 Goldene und 3 Silberne Medallien.jpeg" "$DST/wetzlar-open-2025-medaillen-gold-silber.jpeg"
cp "$SRC/Vermessung durch maschiene eines Schlüssels.jpeg" "$DST/schluessel-vermessung-praezisionsmaschine-wetzlar.jpeg"
cp "$SRC/Elektrisches Türschloss aufgebrochen mit sichtbaren Kabeln.jpeg" "$DST/elektronisches-tuerschloss-aufgebrochen-kabel-sichtbar.jpeg"
cp "$SRC/Aufgebrochen und gelöstem Türsschloss  auf Holz Bank liegend.jpeg" "$DST/demontiertes-tuerschloss-auf-werkbank-wetzlar.jpeg"
cp "$SRC/Glasschrank innerhalb der Schlüsselschmiede.jpeg" "$DST/glasschrank-schloss-auswahl-schluessel-schmiede-wetzlar.jpeg"
cp "$SRC/Türschloss währed aufbrechungs Prozess.jpeg" "$DST/tuerschloss-aufbruch-prozess-nahaufnahme-wetzlar.jpeg"
cp "$SRC/andere Maschiene für schlüssel erstellung.jpeg" "$DST/cnc-schluesselmaschine-schluessel-schmiede-wetzlar.jpeg"
cp "$SRC/Innere des Modernen klick schlosses in alter Tür.jpeg" "$DST/smart-lock-innenleben-nachruestung-holztuer.jpeg"
cp "$SRC/Installierter Tür eingang aus EdelstahlV2.jpeg" "$DST/edelstahl-tueranlage-premium-montage-wetzlar.jpeg"
cp "$SRC/Mina Saad während der Arbeit an dem modernen Klick schloss.jpeg" "$DST/mina-saad-smart-lock-installation-wetzlar.jpeg"
cp "$SRC/vermessung des inneren eines Türschlosses mit Zollstock.jpeg" "$DST/tuerschloss-vermessung-zollstock-schluesseldienst.jpeg"

echo ""
echo "═══════════════════════════════════════════════════"
echo "  PHASE 1b: Bestehende WebPs kopieren"
echo "═══════════════════════════════════════════════════"

cp "$SRC/schluessel-schmiede-wetzlar-aussenansicht-ladengeschaeft.webp" "$DST/"
cp "$SRC/schluessel-schmiede-wetzlar-innenbereich-laden.webp" "$DST/"
cp "$SRC/schluessel-schmiede-wetzlar-schluessel-fraesen-maschine.webp" "$DST/"
cp "$SRC/lockpicking_tueroeffnung_schluesseldienst_wetzlar.webp" "$DST/lockpicking-tueroeffnung-schluesseldienst-wetzlar.webp"
cp "$SRC/schluessel_an_haustuer_schluesseldienst_wetzlar.webp" "$DST/schluessel-an-haustuer-schluesseldienst-wetzlar.webp"
cp "$SRC/schloss_mit_schluessel_tueroeffnung_schluesseldienst_wetzlar.webp" "$DST/schloss-mit-schluessel-tueroeffnung-schluesseldienst-wetzlar.webp"

echo ""
echo "═══════════════════════════════════════════════════"
echo "  VERIFIZIERUNG"
echo "═══════════════════════════════════════════════════"
TOTAL=$(ls "$DST"/*.jpeg "$DST"/*.webp 2>/dev/null | wc -l)
echo "Gesamtdateien in $DST: $TOTAL"
echo "Gesamtgröße:"
du -sh "$DST"
echo ""
echo "✅ SEO-Batch-Umbenennung abgeschlossen!"
